# Generated by Django 5.1.6 on 2025-05-06 10:36

import django.db.models.deletion
import main_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilComposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('texteAccueil', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/public/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/public/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/public/')),
                ('dateDeChangement', models.DateField(blank=True, db_column='dateDeChangement', default=main_app.models.get_todayDate)),
            ],
            options={
                'db_table': 'AccueilComposant',
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeScolaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TPS', 'Toute petite section'), ('PS', 'Petite section'), ('MS', 'Moyenne section'), ('GS', 'Grande section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6E', '6ème'), ('5E', '5ème'), ('4E', '4ème'), ('3E', '3ème')], max_length=3, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('groupe_cycles', models.CharField(choices=[('C1', 'Cycle 1 (Maternelle)'), ('C2', 'Cycle 2 (CP-CE1-CE2)'), ('C3', 'Cycle 3 (CM1-CM2-6ème)'), ('C4', 'Cycle 4 (5ème-4ème-3ème)')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEleve', models.CharField(max_length=255)),
                ('prenomEleve', models.CharField(blank=True, max_length=255)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('emailParent', models.CharField(blank=True, max_length=120, null=True)),
                ('dateDeNaissance', models.DateField(blank=True, db_column='dateDeNaissance', null=True)),
                ('contactParent', models.CharField(max_length=100)),
                ('classeDemande', models.CharField(blank=True, max_length=255)),
                ('dateDeDemande', models.DateField(blank=True, db_column='dateDeDemande', default=main_app.models.get_todayDate)),
                ('statut', models.CharField(choices=[('L', 'L'), ('NL', 'NL')], default='NL', max_length=20)),
            ],
            options={
                'db_table': 'DemandeInscription',
            },
        ),
        migrations.CreateModel(
            name='FooterComposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('emailInfo', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('dateDeChangement', models.DateField(blank=True, db_column='dateDeChangement', default=main_app.models.get_todayDate)),
            ],
            options={
                'db_table': 'FooterComposant',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('typePeriode', models.CharField(choices=[('TRIM', 'Trimestre'), ('SEM', 'Semestre'), ('ANN', 'Année scolaire')], max_length=4)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PresentationComposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titrePresentation', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('textePresentation', models.TextField()),
                ('objectifs', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/public/')),
                ('dateDeChangement', models.DateField(blank=True, db_column='dateDeChangement', default=main_app.models.get_todayDate)),
            ],
            options={
                'db_table': 'PresentationComposant',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('prescolaire', 'prescolaire'), ('primaire', 'primaire'), ('college', 'college'), ('lycee', 'lycee')], default='prescolaire', max_length=20)),
                ('anneeScolaire', models.ForeignKey(blank=True, db_column='anneeScolaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe', to='main_app.anneescolaire')),
                ('titulaire', models.ForeignKey(db_column='titulaire', limit_choices_to={'userprofile__role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main_app.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=main_app.models.get_todayDate)),
                ('heureDebut', models.TimeField(blank=True)),
                ('heureFin', models.TimeField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'userprofile__role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='DomaineEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('typeDomaine', models.CharField(choices=[('TRANS', 'Transversal'), ('DISCIP', 'Disciplinaire'), ('SOCIO', 'Sociocomportemental')], max_length=50)),
                ('ordreAffichage', models.PositiveSmallIntegerField(default=0)),
                ('cycles', models.ManyToManyField(to='main_app.cycle')),
            ],
            options={
                'ordering': ['ordreAffichage'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/etudiant/')),
                ('sexe', models.CharField(choices=[('H', 'H'), ('F', 'F')], default='H', max_length=10)),
                ('religion', models.CharField(blank=True, max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('dateDeNaissance', models.DateField(blank=True, db_column='dateDeNaissance', null=True)),
                ('pere', models.CharField(blank=True, db_column='nomPere', max_length=255, null=True)),
                ('mere', models.CharField(blank=True, db_column='nomMere', max_length=255, null=True)),
                ('classe', models.ForeignKey(blank=True, db_column='classe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='main_app.classe')),
                ('parent', models.ForeignKey(blank=True, db_column='parent', limit_choices_to={'userprofile__role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appreciationGenerale', models.TextField(blank=True)),
                ('pointsForts', models.TextField(blank=True)),
                ('besoins', models.TextField(blank=True)),
                ('projet', models.TextField(blank=True)),
                ('moyenneGenerale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('dateEdition', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.etudiant')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.periode')),
            ],
            options={
                'unique_together': {('eleve', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeurNote', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('appreciation', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bulletin')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.domaineenseignement')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idevenement', models.AutoField(db_column='idEvenement', primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('typeEvent', models.CharField(choices=[('formation', 'formation'), ('annonce', 'annonce'), ('scolaire', 'scolaire'), ('autres', 'autres')], default='scolaire', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datedebut', models.DateField(blank=True, db_column='dateDebut', null=True)),
                ('datefin', models.DateField(blank=True, db_column='dateFin', null=True)),
                ('idpubliepar', models.ForeignKey(db_column='publiePar', limit_choices_to={'userprofile__role': 'direction'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Evenement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PresenceEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('P', 'P'), ('A', 'A'), ('R', 'R')], default='P', max_length=10)),
                ('heureA', models.TimeField(blank=True, null=True)),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cours')),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.etudiant')),
            ],
            options={
                'db_table': 'PresenceEtudiant',
            },
        ),
        migrations.CreateModel(
            name='PresencePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('P', 'P'), ('A', 'A'), ('R', 'R')], default='P', max_length=10)),
                ('date', models.DateField(blank=True, default=main_app.models.get_todayDate)),
                ('heureA', models.TimeField(blank=True, null=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PresencePersonnel',
            },
        ),
    ]
