# Generated by Django 5.1.6 on 2025-05-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='anneeScolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='main_app.anneescolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='presenceetudiant',
            unique_together={('etudiant', 'cours')},
        ),
    ]
