# Generated by Django 5.1.6 on 2025-05-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_periode_anneescolaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationetudiant',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='main_app.bulletin'),
        ),
    ]
