# Generated by Django 5.1.6 on 2025-05-14 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_evaluationetudiant_bulletin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='recrutement/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Buffet', 'Buvette et Restauration'), ('Transport', 'Transport Scolaire')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_depense', models.CharField(choices=[('salaire', 'Salaire'), ('materiel', 'materiel'), ('autre', 'autre')], default='salaire', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=False)),
                ('approuvePar', models.ForeignKey(blank=True, limit_choices_to={'role': 'direction'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbations', to=settings.AUTH_USER_MODEL)),
                ('creerPar', models.ForeignKey(limit_choices_to={'role': 'finance'}, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('poste', models.CharField(blank=True, max_length=50, null=True)),
                ('salarie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dateEmbauche', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CotisationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCotisation', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('raison', models.TextField()),
                ('type_conge', models.CharField(choices=[('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('annuel', 'Congé annuel'), ('permission', 'Permission'), ('autre', 'Autre')], default='annuel', max_length=20)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('annule', 'Annulé')], default='valide', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='main_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_parent', models.CharField(blank=True, default='', max_length=20)),
                ('telephone_direction', models.CharField(blank=True, default='', max_length=20)),
                ('email_destinataire', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('envoyé', 'Envoyé'), ('échec', 'Échec'), ('simulé', 'Simulé')], default='envoyé', max_length=10)),
                ('type_notification', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=10)),
                ('twilio_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.etudiant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('JANVIER', 'JANVIER'), ('FEVRIER', 'FEVRIER'), ('MARS', 'MARS'), ('AVRIL', 'AVRIL'), ('MAI', 'MAI'), ('JUIN', 'JUIN'), ('JUILLET', 'JUILLET'), ('AOUT', 'AOUT'), ('SEPTEMBRE', 'SEPTEMBRE'), ('OCTOBRE', 'OCTOBRE'), ('NOVEMBRE', 'NOVEMBRE'), ('DECEMBRE', 'DECEMBRE')], default='JUIN', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modePaiement', models.CharField(choices=[('Chèques', 'Chèques'), ('Virement', 'Virement'), ('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money')], default='Espèces', max_length=20)),
                ('categorie', models.CharField(choices=[('Ecolage', 'Ecolage'), ('Certificat', 'Certificat de scolarité'), ('Autre', 'Autre')], default='Ecolage', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('datePaiement', models.DateField(auto_now_add=True)),
                ('verrouille', models.BooleanField(default=False)),
                ('effectuePar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='main_app.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='RapportPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('contenu', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classe')),
                ('envoyeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDuRapport', models.DateField(default=django.utils.timezone.now)),
                ('tache', models.CharField(max_length=255)),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
                ('matiere', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_pedagogiques', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=10)),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePaiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(default='Espèce', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.employee')),
            ],
            options={
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
