# Generated by Django 5.1.6 on 2025-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_message_content_type_remove_message_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='historique',
            field=models.ImageField(blank=True, null=True, upload_to='images/historique/'),
        ),
    ]
